### ISSUE TITLE
Rendering issues when residues include hydrogens

### ISSUE THREAD

**Issue by blakesweeney** [biasmv/pv#90]
This can end up drawing things incorrectly if there are hydrogen atoms included. Below is an example of the possible output:

![rendering-issues](https://cloud.githubusercontent.com/assets/330875/7262992/d79ae952-e84b-11e4-9a71-3fbd3d50e664.png)

The purple triangle thing at the top is what I'm referring to. Removing the hydrogen entries makes everything render correctly.

**Comment by biasmv** [comment]
That looks rather bad :(. Can you send me a file to reproduce the problem? I'll take a look.

**Comment by blakesweeney** [comment]
I think the pdb file fragment at this url should do it: http://rna.bgsu.edu/rna3dhub/rest/getCoordinates?coord=2AW7|1|A|C|1265,2AW7|1|A|G|1266,2AW7|1|A|C|1267,2AW7|1|A|G|1268,2AW7|1|A|A|1269,2AW7|1|A|G|1270

Also, do you have plans for showing multiple models and allow superposition of residues?

**Comment by biasmv** [comment]
Hi,

the rendering issue is fixed in master. Could you try if this also fixes the issue for you? The problem was related to the element-from-atom-name guessing code which was incorrectly guessing the element of hydrogen atoms that have a numeric prefix. Now these atoms are correctly classified as hydrogens.

What do mean by showing multiple models? Do you mean loading multiple models from a multi-model PDB file?

A simple residue superposition could be implemented rather quickly. Feel free to file another ticket for this and I'll see when I can get around to implementing it.

Best,
Marco

**Comment by blakesweeney** [comment]
Running the demo script still shows the problem. I put the example data into one of the demo pdbs and opened it and I still see the issue. Is there something else I need to do for that?

And yes, loading multiple models may be useful.

**Comment by blakesweeney** [comment]
Never mind, I tried it in firefox and it looks good. I didn't clear my cache in chrome. Thanks for fixing this so fast!

**Comment by biasmv** [comment]
Good to hear! It's really unfortunate that the caching doesn't work as reliably as it should when using require.js.
